/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  note: [
    'note/introduction',
    {
      label: 'C++',
      type: 'category',
      link: {
        type: 'doc',
        id: 'note/CPP/cpp-guides'
      },
      items: [
        'note/CPP/cpp-bind',
      ]
    },
    {
      label: '杂项',
      type: 'category',
      link: {
        type: 'generated-index',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'note/other',
        },
      ],
    },
  ]
}

module.exports = sidebars
